### PR TITLE
Invoke 3.1.0 Update

### PR DESCRIPTION
**Pull request by BarrenWardo**
Dear Camenduru,

Sorry for this improper pull request. _(I'm not a coding expert, just an enthusiast)_

Here are few things I've done :
1. Invoke updated to 3.1.0.
2. Solved issue of Unified Canvas error.
3. Made Realistic Vision 5.1 + Inpainting Model as default. (Not Important)
4. Addition of few loras and controlnets. (Not Important)

Here are few things you should be looking into :
1. Errors or mistakes in my Colab version
2. After some time of use, second cell gets completed rather keep on running. The server will be still active but generation won't happen.
3. The RAM usage just keeps on increasing after every use but VRAM only gets used for upto 3 GB Max which is a major concern because it stops the colab as soon as the RAM limit is reached. ( **Major Concern** )

I hope this helps in some way to update this git a little faster.

### CODE REVIEW

**Comment by almfahd41** [comment]
@BarrenWardo 

hello 

how to add the Controlnet QR Code Monster v2 For SD-1.5  ?

https://huggingface.co/monster-labs/control_v1p_sd15_qrcode_monster

**Comment by BarrenWardo** [comment]
> @BarrenWardo
> 
> hello
> 
> how to add the Controlnet QR Code Monster v2 For SD-1.5 ?
> 
> https://huggingface.co/monster-labs/control_v1p_sd15_qrcode_monster

@almfahd41 

This is not the right place to discuss it. Please raise a issue on my forked repo so that we can discuss it there.

**Comment by BarrenWardo** [comment]
@camenduru 

Sorry for pinging but whenever you get free can you check this request and update it.

Thank You!

**Comment by camenduru** [comment]
Hi @BarrenWardo 👋 thanks for the PR ❤ let's add your colab to the Readme so you don't need to send a PR each time you update your colab

https://colab.research.google.com/github/BarrenWardo/InvokeAI-colab/blob/main/InvokeAI.ipynb

**Comment by BarrenWardo** [comment]
THANKS !!

**Pull request closed without merging**
